spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**, /cart/**
          filters:
            - "RewritePath=/(?<segment>.*),/api/${segment}"
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

# http://localhost:8080/api/users -> http://localhost:8082/api/users
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

