spring:
  h2:
    console:
      enabled: true  # Enables the H2 console for web-based access
      path: /h2-console # Specifies the URL path for the H2 console
  datasource:
    url: jdbc:h2:mem:testdb # Connects to an in-memory database named 'testdb'
    # For file-based persistence, use: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver # Specifies the H2 JDBC driver
    username: sa # Default username for H2
    password: # Default empty password for H2
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the schema based on entities
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Specifies the Hibernate dialect for H2

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

app:
  message: "Hello Order!"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 5s
  ratelimiter:
    instances:
      rateBreaker:
        timeout-duration: 0
        limit-refresh-period: 4s
        limit-for-period: 2
